### ISSUE TITLE
Postgrest-go Repository

### ISSUE THREAD

**Issue by Fritte795** [nedpals/supabase-go#38]
Hey @nedpals ,  
unfortunately I have no other way to reach out.   
  
Two requests: 
1. Could you please enable "Issues" in [postgrest-go](https://github.com/nedpals/postgrest-go)
2. Could you also please prepare a new Release (Tag) so that I could implement the new library version into the supabase repo?

**Comment by nedpals** [comment]
Hi! Sorry if I am unresponsive in replying some of the issues. To address your concerns:

1. Sure thing. However, I would like to propose an alternative. Move postgrest-go into the main repo instead so it would be easier to track and update changes since the only reason postgrest-go exists because of this.

2. As for the new release, will be doing it now. Thanks for your concern

**Comment by Fritte795** [comment]
I did not expect such an immediate response, so I can't say you are unresponsive :)  
  
1. It depends on the purpose of the projects. If the goal is to mimic the official javascript supabase repositories ( [supabase-js](https://github.com/supabase/supabase-js/) and [postgrest-js](https://github.com/supabase/postgrest-js/) ) to merge the to repositories would not be ideal. Merging them would indeed provide easier maintenance but would prevent the postgrest-go library on its own. 
2. Thank you! If the release is ready, I will include it here.

**Comment by nedpals** [comment]
> Merging them would indeed provide easier maintenance but would prevent the postgrest-go library on its own.

The Supabase community already had a successful Go implementation of the [postgrest-go](https://github.com/supabase-community/postgrest-go) so I don't think it does not make sense anymore to keep it as a separate library. In relation to that, I don't have the energy yet to migrate this into with supabase's as they might have different ways to do things versus what we have now but that will be inevitable in the near future.

> Thank you! If the release is ready, I will include it here.

0.4.0 has already been released. You're welcome :wink: : https://github.com/nedpals/supabase-go/releases/tag/v0.4.0

**Comment by Fritte795** [comment]
I was not aware of that library. As I have to set a custom TLS Route Configuration for the Postgrest http.client to accept additional root CAs to communicate with a postgres database I believe I have to either merge your postgrest-go into this repo or use the repository you just linked. 

I will stay in touch and prepare a merge request. Have a great day.
