### ISSUE TITLE
Provision redirectTo for the go sdk

### ISSUE THREAD

**Issue by saintmalik** [nedpals/supabase-go#52]
is it possible to pass the redirectTO parameter for the signup confirmation mail sent by supabase just like its done in the js syntax 

`async function signUpNewUser() {
  const { data, error } = await supabase.auth.signUp({
    email: 'example@email.com',
    password: 'example-password',
    options: {
      emailRedirectTo: 'https://example.com/welcome',
    },
  })
}`

**Comment by emilkm** [comment]
Hi @saintmalik 

I recently added **ResetPasswordForEmailWithRedirectUrl** method to my fork

https://github.com/emilkm/supabase-go/tree/recover_redirect_to

and seeing your comment, just added **SignUpWithRedirectUrl**, plus a couple of small fixes.

I haven't had the time to test **SignUpWithRedirectUrl**. But did test my **ResetPasswordForEmailWithRedirectUrl** method and that worked for me.

Method of calling **SignUpWithRedirectUrl** is not the same syntax as the TypeScript/JS client. I followed the pattern of the library, and that by another contributor that recently added **InviteUserByEmailWithData**

So you still have the existing **SignUp** method, and a new **SignUpWithRedirectUrl** method, with redirectTo being the last parameter.

Library is small enough so you can easily stick the folder into your project to test if it works.

**Comment by saintmalik** [comment]
thanks for this @emilkm , i will give it a try in my next project
